AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Housemates backend API

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref TableName

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  ProjectName:
    Type: String
    Default: housemates
  TableName:
    Type: String
    Description: DynamoDB table name
  TableArn:
    Type: String
    Description: DynamoDB table ARN

Metadata:
  LambdaBuildConfig: &lambda-build
    BuildMethod: esbuild
    BuildProperties:
      Minify: true
      Target: es2022
      Sourcemap: false
      EntryPoints:
        - handler.ts
      External:
        - "@aws-sdk/*"

Resources:
  HousematesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${ProjectName}-api"
      Description: "500 lambda functions"
      StageName: !Ref Environment
      # TODO: Add Auth authorization
      # Auth:
      #   DefaultAuthorizer: CognitoAuthorizer
      #   Authorizers:
      #     CognitoAuthorizer:
      #       UserPoolArn: !Ref CognitoUserPoolArn

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-hello-world"
      CodeUri: functions/hello-world/
      Handler: handler.handler
      Description: Hello world Lambda for API Gateway
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        HelloGet:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /hello
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - handler.ts

  CreateAnnouncementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-create-announcement"
      CodeUri: functions/create-announcement
      Handler: handler.handler
      Description: Creates Announcement
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        AnnouncementPost:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /announcements
            Method: POST
    Metadata: *lambda-build
  CreateChoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-create-chore"
      CodeUri: functions/create-chore/
      Handler: handler.handler
      Description: Create chore
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ChorePost:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /chores
            Method: POST
    Metadata: *lambda-build

  CreateHouseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-create-house"
      CodeUri: functions/create-house/
      Handler: handler.handler
      Description: Create house and expenses bucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        HousePost:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /house
            Method: Post
    Metadata: *lambda-build
  CreateExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-create-expense"
      CodeUri: functions/create-expense/
      Handler: handler.handler
      Description: Create expense
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ExpensePost:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /expenses
            Method: Post
    Metadata: *lambda-build
  CreateShoppingItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-create-shopping-item"
      CodeUri: functions/create-shoppingitem/
      Handler: handler.handler
      Description: Create shopping item in list
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ShoppingItemPost:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /shopping/item
            Method: Post
    Metadata: *lambda-build
  GetAnnouncements:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-get-announcements"
      CodeUri: functions/get-announcements/
      Handler: handler.handler
      Description: Get announcements from house id
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        AnnouncementsGet:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /announcements
            Method: GET
    Metadata: *lambda-build
  GetChoresByHouse:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-get-chores-house"
      CodeUri: functions/get-chore-house/
      Handler: handler.handler
      Description: Get chores from house id
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ChoresGet:
          Type: Api
          Properties:
            RestApiId: !Ref HousematesApi
            Path: /chores
            Method: GET
    Metadata: *lambda-build
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${HousematesApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
  HelloWorldFunctionArn:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
